name: download-zotero-pdfs

on:
  workflow_dispatch:
  push:
    branches:
      - pdfs

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python pdfs/pdfs.py